### ISSUE TITLE
Console causes uncontrolled turning

### ISSUE THREAD

**Issue by Luomu** [pioneerspacesim/pioneer#2735]
1. Start a new game, blast off
2. Start turning (yaw) left
3. Open console while turn is underway
   The ship begins rapidly spinning in the opposite direction.

**Comment by Bodasey** [comment]
fixed with #5085 ?

**Comment by The-EG** [comment]
> fixed with #5085 ?

I can't get it to happen now...and considering the input binding system *and* the console have been refactored since this happened, it's not likely this is still an issue in any case.

**Comment by Web-eWorks** [comment]
Yup, this was specifically fixed with the new input system. Thanks for finding (and closing) this, @The-EG!
