### ISSUE TITLE
Can't load saved games in Arch-based distros

### ISSUE THREAD

**Issue by Raiz1337** [pioneerspacesim/pioneer#3387]
When i try to load a game in pioneer the game crashes immediately, i asked people @ the IRC they told me to post this on the issue tracker (( Note: this issue is only for Arch-based distros ))

**Comment by Tichy** [comment]
I can confirm this.

Just started from Earth, heading to Uranus. Saved. Loaded. Switched to max time acceleration. In a couple of seconds the game crashed leaving these messages on console.

```
cleanTSTable:total:48,active:40,removed:0
deneb jump status is not OK
WJ-3158 docked with Enki Catena ship:deneb
pioneer: LuaTable.h:100: LuaTable::LuaTable(lua_State*, int): Assertion `(lua_type(m_lua, (m_index)) == 5)' failed.
[1]    14389 abort (core dumped)  pioneer
```

This is my savefile.

https://app.box.com/s/135nhm2kga41ek5crmjqilov95m1y2zs

Pioneer is compiled on my machine using the AUR package.
https://aur.archlinux.org/packages/pioneer-git/

**Comment by impaktor** [comment]
Are you both on Arch "Stable"?
I know Arch Testing just got GCC 5.0. If that can have something to do with it?

**Comment by Tichy** [comment]
On 2015-05-14 10:50, Karl F wrote:
> Are you both on Arch "Stable"?
>  I know Arch Testing just got GCC 5.0. If that can have something to
> do with it?

I'm on stable.

**Comment by laarmen** [comment]
Do you compile the game or use the pre-built thingy?

**Comment by Tichy** [comment]
On 2015-05-14 22:24, Simon Chopin wrote:
> Do you compile the game or use the pre-built thingy?

Pioneer is compiled on my machine using the AUR package.
https://aur.archlinux.org/packages/pioneer-git/

Which is an automated way to clone the git repo, compile it and build a 
binary package.

**Comment by jmf** [comment]
I can confirm this on my arch, too.
I am compiiling from git repo manually.
Stable archlinux, Linux 4.0.1-1-ARCH #1 SMP PREEMPT x86_64
gcc 4.9.2
Lua 5.2.4

`pioneer: LuaTable.h:100: LuaTable::LuaTable(lua_State*, int): Assertion '(lua_type(m_lua, (m_index)) == 5)' failed.`
`Aborted (core dumped)`

**Comment by laarmen** [comment]
What about when using an old version ? Like ab02e8604047440193dfad3046e9094e0a0fb439

**Comment by Raiz1337** [comment]
There's no stable arch, lol, i get pioneer from the AUR (( It's compiled from the source code using PKGBUILD script )).

**Comment by jmf** [comment]
@Raiz1337: There is no real "stable" version, but there is a testing repository. It contains software that isn't compatible with everything in the other repos. It contains gcc 5, for example, while gcc 4.9.x is current in the other repos.
When you use the AUR script, you can insert some commands to revert it to an older version.
Or you could just git clone it, revert to an older version and compile it by hand, using the instructions that come with pioneer or the ones in the PKGBUILD.

**Comment by jmf** [comment]
Here's a backtrace of the bug:
http://pastie.org/pastes/10208384/text?key=skybbd6hndq3jyy4r00ehq

**Comment by Tichy** [comment]
Another backtrace
http://sprunge.us/LiPP

**Comment by laarmen** [comment]
@jmf I can haz a try on an older version ? ab02e86 would be a fine candidate.

**Comment by jmf** [comment]
ab02e86 seems to work.

**Comment by laarmen** [comment]
OK, now we're getting somewhere. Would you be willing to bisect this for us
to narrow down when the bug was introduced ? I glanced over the git logs
without finding any obvious suspect !

**Comment by impaktor** [comment]
so @jmf reported that fff40798a981ddefbc699b0b5a19bb56a8ca6be4 is the first bad commit. Which is pretty strange.


That would mean that adding Cargo run mission did not break it two commits earlier, so 903b2e0fe37118ab048e2b97d7c06186552512e7 works? @jmf could you please test that commit a bit?

**Comment by laarmen** [comment]
Can anybody confirm the issue has been fixed ?

**Comment by impaktor** [comment]
worth mentioning we have a new build out with the fix, for anyone who want's to test it
http://pioneerspacesim.net/download

**Comment by jmf** [comment]
The latest git version still crashes.
I'll do a new git bisect as soon as possible, since it seems that my old bisect wasn't done correctly and post the results here.

**Comment by johnbartholomew** [comment]
Bisect may be misleading if the problem doesn't happen 100% of the time, or
if there are multiple bugs that produce similar crashes.

If possible, please get a stack trace. Even better, use valgrind or address
sanitiser to help detect the problem(s) more reliably.

**Comment by johnbartholomew** [comment]
Ok, I'm now getting what looks like the same crash that was posted by Tichy and jmf, it just happened a while after I loaded a save-game. I guess I fixed some other unrelated problem :-P

**Comment by johnbartholomew** [comment]
@jmf, could you test #3407?
