### ISSUE TITLE
Crash at '6.8 billion years'

### ISSUE THREAD

**Issue by cakenggt** [pioneerspacesim/pioneer#3439]
With a fresh install of pioneer 20150810 the game crashes when loading at '6.8 billion years'.

opengl.txt
```
OpenGL version 3.1.0 - Build 9.18.10.3204, running on Intel Intel(R) HD Graphics 4600
Available extensions:
Shading language version: 1.40 - Build 9.18.10.3204
  GL_EXT_blend_minmax
  GL_EXT_blend_subtract
  GL_EXT_blend_color
  GL_EXT_abgr
  GL_EXT_texture3D
  GL_EXT_clip_volume_hint
  GL_EXT_compiled_vertex_array
  GL_SGIS_texture_edge_clamp
  GL_SGIS_generate_mipmap
  GL_EXT_draw_range_elements
  GL_SGIS_texture_lod
  GL_EXT_rescale_normal
  GL_EXT_packed_pixels
  GL_EXT_texture_edge_clamp
  GL_EXT_separate_specular_color
  GL_ARB_multitexture
  GL_ARB_map_buffer_alignment
  GL_ARB_conservative_depth
  GL_EXT_texture_env_combine
  GL_EXT_bgra
  GL_EXT_blend_func_separate
  GL_EXT_secondary_color
  GL_EXT_fog_coord
  GL_EXT_texture_env_add
  GL_ARB_texture_cube_map
  GL_ARB_transpose_matrix
  GL_ARB_internalformat_query
  GL_ARB_texture_env_add
  GL_IBM_texture_mirrored_repeat
  GL_EXT_multi_draw_arrays
  GL_SUN_multi_draw_arrays
  GL_NV_blend_square
  GL_ARB_texture_compression
  GL_3DFX_texture_compression_FXT1
  GL_EXT_texture_filter_anisotropic
  GL_ARB_texture_border_clamp
  GL_ARB_point_parameters
  GL_ARB_texture_env_combine
  GL_ARB_texture_env_dot3
  GL_ARB_texture_env_crossbar
  GL_EXT_texture_compression_s3tc
  GL_ARB_shadow
  GL_ARB_window_pos
  GL_EXT_shadow_funcs
  GL_EXT_stencil_wrap
  GL_ARB_vertex_program
  GL_EXT_texture_rectangle
  GL_ARB_fragment_program
  GL_EXT_stencil_two_side
  GL_ATI_separate_stencil
  GL_ARB_vertex_buffer_object
  GL_EXT_texture_lod_bias
  GL_ARB_occlusion_query
  GL_ARB_fragment_shader
  GL_ARB_shader_objects
  GL_ARB_shading_language_100
  GL_ARB_texture_non_power_of_two
  GL_ARB_vertex_shader
  GL_NV_texgen_reflection
  GL_ARB_point_sprite
  GL_ARB_fragment_program_shadow
  GL_EXT_blend_equation_separate
  GL_ARB_depth_texture
  GL_ARB_texture_rectangle
  GL_ARB_draw_buffers
  GL_ARB_color_buffer_float
  GL_ARB_half_float_pixel
  GL_ARB_texture_float
  GL_ARB_pixel_buffer_object
  GL_EXT_framebuffer_object
  GL_ARB_draw_instanced
  GL_ARB_half_float_vertex
  GL_ARB_occlusion_query2
  GL_EXT_draw_buffers2
  GL_WIN_swap_hint
  GL_EXT_texture_sRGB
  GL_ARB_multisample
  GL_EXT_packed_float
  GL_EXT_texture_shared_exponent
  GL_ARB_texture_rg
  GL_ARB_texture_compression_rgtc
  GL_NV_conditional_render
  GL_EXT_texture_swizzle
  GL_ARB_texture_gather
  GL_ARB_sync
  GL_ARB_framebuffer_sRGB
  GL_EXT_packed_depth_stencil
  GL_ARB_depth_buffer_float
  GL_EXT_transform_feedback
  GL_ARB_transform_feedback2
  GL_ARB_draw_indirect
  GL_EXT_framebuffer_blit
  GL_EXT_framebuffer_multisample
  GL_ARB_framebuffer_object
  GL_EXT_texture_array
  GL_EXT_texture_integer
  GL_ARB_map_buffer_range
  GL_EXT_texture_snorm
  GL_ARB_blend_func_extended
  GL_INTEL_performance_queries
  GL_ARB_copy_buffer
  GL_ARB_sampler_objects
  GL_NV_primitive_restart
  GL_ARB_seamless_cube_map
  GL_ARB_uniform_buffer_object
  GL_ARB_depth_clamp
  GL_ARB_vertex_array_bgra
  GL_ARB_shader_bit_encoding
  GL_ARB_draw_buffers_blend
  GL_ARB_geometry_shader4
  GL_EXT_geometry_shader4
  GL_ARB_texture_query_lod
  GL_ARB_explicit_attrib_location
  GL_ARB_draw_elements_base_vertex
  GL_ARB_instanced_arrays
  GL_ARB_base_instance
  GL_ARB_fragment_coord_conventions
  GL_EXT_gpu_program_parameters
  GL_ARB_texture_buffer_object_rgb32
  GL_ARB_compatibility
  GL_ARB_texture_rgb10_a2ui
  GL_ARB_texture_multisample
  GL_ARB_vertex_type_2_10_10_10_rev
  GL_ARB_timer_query
  GL_ARB_tessellation_shader
  GL_ARB_vertex_array_object
  GL_ARB_provoking_vertex
  GL_ARB_sample_shading
  GL_ARB_texture_cube_map_array
  GL_ARB_gpu_shader5
  GL_ARB_gpu_shader_fp64
  GL_ARB_shader_subroutine
  GL_ARB_transform_feedback3
  GL_ARB_transform_feedback_instanced
  GL_EXT_texture_storage
  GL_ARB_texture_storage
  GL_INTEL_map_texture
  GL_ARB_ES2_compatibility
  WGL_EXT_depth_float
  WGL_ARB_buffer_region
  WGL_ARB_extensions_string
  WGL_ARB_make_current_read
  WGL_ARB_pixel_format
  WGL_ARB_pbuffer
  WGL_EXT_extensions_string
  WGL_EXT_swap_control
  WGL_EXT_swap_control_tear
  WGL_ARB_multisample
  WGL_ARB_pixel_format_float
  WGL_ARB_framebuffer_sRGB
  WGL_ARB_create_context
  WGL_ARB_create_context_profile
  WGL_EXT_pixel_format_packed_float
  WGL_EXT_create_context_es2_profile

Implementation Limits:
GL_MAX_COMBINED_TEXTURE_IMAGE_UNITS = 80
GL_MAX_CUBE_MAP_TEXTURE_SIZE = 8192
GL_MAX_DRAW_BUFFERS = 8
GL_MAX_ELEMENTS_INDICES = 1.04858e+006
GL_MAX_ELEMENTS_VERTICES = 1.04858e+006
GL_MAX_FRAGMENT_UNIFORM_COMPONENTS = 4096
GL_MAX_TEXTURE_IMAGE_UNITS = 16
GL_MAX_TEXTURE_LOD_BIAS = 15
GL_MAX_TEXTURE_SIZE = 8192
GL_MAX_VERTEX_ATTRIBS = 16
GL_MAX_VERTEX_TEXTURE_IMAGE_UNITS = 16
GL_MAX_VERTEX_UNIFORM_COMPONENTS = 4096
GL_NUM_COMPRESSED_TEXTURE_FORMATS = 6
GL_SAMPLE_BUFFERS = 1
GL_SAMPLES = 4
GL_ALIASED_LINE_WIDTH_RANGE = 1, 7
GL_MAX_VIEWPORT_DIMS = 8192, 8192
GL_SMOOTH_LINE_WIDTH_RANGE = 0, 6.99219
GL_SMOOTH_POINT_SIZE_RANGE = 1, 20

Compressed texture formats:
  0x83f0
  0x83f2
  0x83f3
  0x83f1
  0x86b0
  0x86b1
```

output.txt
```
ver 20150810 (0bd8149) on: Windows

Hardware information: 
  		OEM ID: 0
  		Number of processors: 4
  		Page size: 4096
  		Processor type: 586
  		Minimum application address: 10000
  		Maximum application address: 7ffeffff
  		Active processor mask: 15

Windows 7 (Service Pack 1)
SDL Version 2.0.3
Initialized OpenGL 3.1, with extensions, renderer
invalid axis binding '' in config file for BindAxisPitch
invalid axis binding '' in config file for BindAxisRoll
invalid axis binding '' in config file for Bind
```

**Comment by impaktor** [comment]
Yes, this build is just a few hours old. Did previous version (which one?) of pioneer work for you?

**Comment by cakenggt** [comment]
Versions 20150715 and 20150710 fail at this point too.

**Comment by impaktor** [comment]
@cakenggt have you played pioneer earlier on that machine at all?

If so, do you know which version?

**Comment by cakenggt** [comment]
Yes, I played it with version 20140930. I thought that it might be the
common problem in the FAQ where the computer can't supprot OpenGL 3.1, but
I ran OpenGL Extensions Viewer and I get that I have OpenGL Version 4.0 and
Driver Version 3.0.0.0

**Comment by impaktor** [comment]
Thanks. That's useful knowledge.

**Comment by impaktor** [comment]
@fluffyfreak might have wisdom to share.

**Comment by fluffyfreak** [comment]
What happens at 6.8 Billion years? I've been trying it on the hardware that I have but it works.

I'm off on holiday tomorrow so won't be able to investigate until I get back when I will be a little bit busy catching up on work.

**Comment by cakenggt** [comment]
It gives me that windows dialog box that says "pioneer.exe has stopped
responding..." immediately when getting to that point, not after a long
wait like with other programs when they crash.

**Comment by cakenggt** [comment]
The same crash happens at 6.8 billion on 20150912 as well.

**Comment by impaktor** [comment]
How is it, do we dump crash report into the [config dir](http://pioneerwiki.com/wiki/FAQ#Technical_FAQ)?

**Comment by granger44** [comment]
Just downloaded 20151109 and am having this issue.

**Comment by impaktor** [comment]
@granger44 I'm willing to bet you can fix it by removing the sgm files in the models directory, please see #3525 (short version: the latest build on the pioneer download page isn't as it is supposed to be). 

@fluffyfreak In fact, isn't this issue the same as that one?

**Comment by fluffyfreak** [comment]
Yes, same issue, need to set @robn on it ;)

**Comment by granger44** [comment]
Deleting the sgm files got me past 6.8 billion years and then another crash at 8.2 billion.  I'm running Windows 8.1.

**Comment by fluffyfreak** [comment]
@granger44 there's two files called `opengl.txt` and `output.txt` in your `1/My Documents/Pioneer/` folder, can you upload them to [pastebin](http://pastebin.com/) so we can see what errors you are getting please?

Also when you say "crash" what do you mean? Does it give an error message?

**Comment by laarmen** [comment]
@granger44 are you sure it was a crash and not a hang? Recompiling the models can sometimes be so long that the OS thinks the application is not responding.

**Comment by granger44** [comment]
Here's the error message I got.  Maybe it's related to this issue or maybe not.
![image](https://cloud.githubusercontent.com/assets/6485369/11164307/9d80452a-8aba-11e5-9523-1044c55561a6.png)

**Comment by fluffyfreak** [comment]
Ooh very interesting, suggests there's something really wrong.

**Comment by impaktor** [comment]
Hm, L247 in SpaceStationType.cpp

**Comment by laarmen** [comment]
Which is a blank line between functions on the current master... Yay!

**Comment by laarmen** [comment]
Ahem, spoke too soon. SpaceStationTYPE.cpp, damnit!

**Comment by impaktor** [comment]
Yes, me and @laarmen did stuff to spacestations recently (#3505), so I wonder if we should feel guilty here? 

e292532, 754a272

**Comment by laarmen** [comment]
I don't think so. Methinks this piece of code runs before the patched code, when reading the definitions of the Space Station models.

**Comment by JustinKerbice** [comment]
Hi,

I've got a similar, but different, crash on a band new game (pioneer-20151109-win32) on win7 64b, in output.txt:
(I just double click on pioneer executable, got "6.8 billions years" progress then an error pop-up)

> Initialized OpenGL 3.1, with extensions, renderer
> invalid axis binding '' in config file for BindAxisPitch
> invalid axis binding '' in config file for BindAxisRoll
> invalid axis binding '' in config file for BindAxisYaw
> started 7 worker threads
> ShipType::Init()
> Lua::Init()
> Server agent disabled
> GalaxyGenerator::Init()
> Creating new galaxy generator 'legacy' version 1
> Number of factions added: 103
> StarSystemCache: misses: 2069, slave hits: 0, master hits: 0
> SectorCache: misses: 1458, slave hits: 0, master hits: 10348
> FaceParts::Init()
> Face Generation source images loaded.
> new ModelCache
> Shields::Init
> BaseSphere::Init
> CityOnPlanet::Init
> terminate called after throwing an instance of 'ModelCache::ModelNotFoundException'
>   what():  Could not find model

deleting player profile in My doc folder doesn't change anything.

Quite disappointing for a new player experience !

**Comment by impaktor** [comment]
@JustinKerbice so you've tried deleting the sgm files in data/models dir? Have you tried the build from November 5th? [link](http://sourceforge.net/projects/pioneerspacesim/files/)

@robn or @eloquentmess (or anyone else with sourceforge-access) if you have time, could you please remove the latest build (Nov 9) from sourceforge?

**Comment by JustinKerbice** [comment]
@impaktor: Just use the win32 build; and deleting those sgm files did it, the game works by removing them, why ? Don't know. If they are shipped with the game, perhaps removing them from archive would be a good idea. Thanks.

**Comment by impaktor** [comment]
@JustinKerbice the current build is broken, we know about it, but our build-magician is currently engaged elswhere, but we hope to have it fixed when he's back. sgm-files just speed up loading of the game. http://spacesimcentral.com/ssc/topic/5296-wont-open/

**Comment by impaktor** [comment]
OK, so several people here report the crash, some confirmd removing the sgm files fixed it, others have not replied, and either way, the problem is fixed in the new build (we hope).

**Comment by cakenggt** [comment]
I have run the 20160404 build and am still getting the crash at 6.8 billion years.

**Comment by fluffyfreak** [comment]
@cakenggt did you extract 20160404 over the older Pioneer folder or did you delete the old folder and do a clean extract of 20160404?

**Comment by cakenggt** [comment]
@fluffyfreak I completely deleted my old folder and just ran 20160404 from the new folder I extracted it to.

**Comment by fluffyfreak** [comment]
@cakenggt ok do you have the contents of the `output.txt` file?

**Comment by cakenggt** [comment]
@fluffyfreak 
`output.txt`
```
ver 20160404 (646f6c0) on: Windows

Hardware information: 
  		OEM ID: 0
  		Number of processors: 4
  		Page size: 4096
  		Processor type: 586
  		Minimum application address: 00010000
  		Maximum application address: 7ffeffff
  		Active processor mask: 15

Windows 7 (Service Pack 1)
SDL Version 2.0.3
Initialized OpenGL 3.1, with extensions, renderer
invalid axis binding '' in config file for BindAxisPitch
invalid axis binding '' in config file for BindAxisRoll
invalid axis binding '' in config file for B
```

**Comment by fluffyfreak** [comment]
@cakenggt if you could download the latest build from http://pioneerspacesim.net/ then open up the `config.ini` file and make these two changes:
> DisableEclipse=0
> UseTextureCompression=1
become:
> DisableEclipse=1
> UseTextureCompression=0

Then give that another try. I made some changes to the texture building and there have been numerous other updates too.

**Comment by cakenggt** [comment]
I couldn't find the `config.ini` file at first, so I attempted to start up the game, and it actually worked. I can play the game just like normal again, and I didn't actually change any settings.

Thanks!

**Comment by fluffyfreak** [comment]
Awesome news! Thanks for all the testing @cakenggt :)
