### ISSUE TITLE
gui warning

### ISSUE THREAD

**Issue by alex199568** [pioneerspacesim/pioneer#3478]
When I start the game on Ubuntu 14.04 I have GL_INVALID_ENUM. The game still loads and I can start a new game. I tried to install libtxc-dxtn, but this didn't help. But the gui issue is that the warning about GL_INVALID_ENUM not only prints to console, but also via messagebox every frame. Thus, to start a game I have to close hundreds of them.

**Comment by fluffyfreak** [comment]
Hi @alex199568 could you upload the contents of the `opengl.txt` & `output.txt` files we create when the game is run?

That should give me the information I need about your GPU etc.

**Comment by impaktor** [comment]
```
<magagnarata> hi, I'm getting problems when running pioneer on ubuntu 14.04                                                                  
              x86_64, like a lot of 'GL_INVALID_ENUM' gui messages during                                                                    
              universe simulation startup.
```
And:
```
OpenGL version 3.1 (Core Profile) Mesa 10.1.3, running on Intel Open Source Technology Center Mesa DRI Intel(R) Sandybridge Mobile 
Available extensions:
Shading language version: 1.40
  GL_ARB_ES2_compatibility
  GL_ARB_ES3_compatibility
  GL_ARB_base_instance
  GL_ARB_blend_func_extended
  GL_ARB_clear_buffer_object
  GL_ARB_copy_buffer
  GL_ARB_debug_output
  GL_ARB_depth_buffer_float
  GL_ARB_depth_clamp
  GL_ARB_draw_buffers
  GL_ARB_draw_buffers_blend
  GL_ARB_draw_elements_base_vertex
  GL_ARB_draw_instanced
  GL_ARB_explicit_attrib_location
  GL_ARB_fragment_coord_conventions
  GL_ARB_fragment_shader
  GL_ARB_framebuffer_object
  GL_ARB_framebuffer_sRGB
  GL_ARB_get_program_binary
  GL_ARB_half_float_pixel
  GL_ARB_half_float_vertex
  GL_ARB_instanced_arrays
  GL_ARB_internalformat_query
  GL_ARB_invalidate_subdata
  GL_ARB_map_buffer_alignment
  GL_ARB_map_buffer_range
  GL_ARB_occlusion_query2
  GL_ARB_pixel_buffer_object
  GL_ARB_point_sprite
  GL_ARB_provoking_vertex
  GL_ARB_robustness
  GL_ARB_sample_shading
  GL_ARB_sampler_objects
  GL_ARB_seamless_cube_map
  GL_ARB_shader_bit_encoding
  GL_ARB_shader_objects
  GL_ARB_shader_texture_lod
  GL_ARB_shading_language_packing
  GL_ARB_shading_language_420pack
  GL_ARB_sync
  GL_ARB_texture_buffer_object
  GL_ARB_texture_buffer_object_rgb32
  GL_ARB_texture_buffer_range
  GL_ARB_texture_compression_rgtc
  GL_ARB_texture_cube_map_array
  GL_ARB_texture_float
  GL_ARB_texture_mirror_clamp_to_edge
  GL_ARB_texture_multisample
  GL_ARB_texture_non_power_of_two
  GL_ARB_texture_query_levels
  GL_ARB_texture_query_lod
  GL_ARB_texture_rectangle
  GL_ARB_texture_rgb10_a2ui
  GL_ARB_texture_rg
  GL_ARB_texture_storage
  GL_ARB_texture_storage_multisample
  GL_ARB_texture_swizzle
  GL_ARB_timer_query
  GL_ARB_uniform_buffer_object
  GL_ARB_vertex_array_bgra
  GL_ARB_vertex_array_object
  GL_ARB_vertex_attrib_binding
  GL_ARB_vertex_shader
  GL_ARB_vertex_type_10f_11f_11f_rev
  GL_ARB_vertex_type_2_10_10_10_rev
  GL_EXT_abgr
  GL_EXT_blend_equation_separate
  GL_EXT_draw_buffers2
  GL_EXT_draw_instanced
  GL_EXT_framebuffer_blit
  GL_EXT_framebuffer_multisample
  GL_EXT_framebuffer_multisample_blit_scaled
  GL_EXT_framebuffer_sRGB
  GL_EXT_packed_depth_stencil
  GL_EXT_packed_float
  GL_EXT_pixel_buffer_object
  GL_EXT_provoking_vertex
  GL_EXT_shader_integer_mix
  GL_EXT_texture_array
  GL_EXT_texture_compression_dxt1
  GL_ANGLE_texture_compression_dxt3
  GL_ANGLE_texture_compression_dxt5
  GL_EXT_texture_compression_rgtc
  GL_EXT_texture_compression_s3tc
  GL_EXT_texture_filter_anisotropic
  GL_EXT_texture_integer
  GL_EXT_texture_shared_exponent
  GL_EXT_texture_snorm
  GL_EXT_texture_sRGB
  GL_EXT_texture_sRGB_decode
  GL_EXT_texture_swizzle
  GL_EXT_timer_query
  GL_EXT_transform_feedback
  GL_EXT_vertex_array_bgra
  GL_OES_EGL_image
  GL_OES_read_format
  GL_KHR_debug
  GL_3DFX_texture_compression_FXT1
  GL_AMD_draw_buffers_blend
  GL_AMD_performance_monitor
  GL_AMD_seamless_cubemap_per_texture
  GL_AMD_shader_trinary_minmax
  GL_APPLE_object_purgeable
  GL_ATI_blend_equation_separate
  GL_ATI_texture_float
  GL_IBM_multimode_draw_arrays
  GL_MESA_pack_invert
  GL_MESA_texture_signed_rgba
  GL_NV_conditional_render
  GL_NV_depth_clamp
  GL_NV_packed_depth_stencil
  GL_S3_s3tc

Implementation Limits:
GL_MAX_COMBINED_TEXTURE_IMAGE_UNITS = 32
GL_MAX_CUBE_MAP_TEXTURE_SIZE = 2048
GL_MAX_DRAW_BUFFERS = 8
GL_MAX_ELEMENTS_INDICES = 3000
GL_MAX_ELEMENTS_VERTICES = 3000
GL_MAX_FRAGMENT_UNIFORM_COMPONENTS = 16384
GL_MAX_TEXTURE_IMAGE_UNITS = 16
GL_MAX_TEXTURE_LOD_BIAS = 14
GL_MAX_TEXTURE_SIZE = 8192
GL_MAX_VERTEX_ATTRIBS = 16
GL_MAX_VERTEX_TEXTURE_IMAGE_UNITS = 16
GL_MAX_VERTEX_UNIFORM_COMPONENTS = 16384
GL_NUM_COMPRESSED_TEXTURE_FORMATS = 5
GL_SAMPLE_BUFFERS = 1
GL_SAMPLES = 4
GL_ALIASED_LINE_WIDTH_RANGE = 1, 5
GL_MAX_VIEWPORT_DIMS = 16384, 16384
GL_SMOOTH_LINE_WIDTH_RANGE = 1, 5
GL_SMOOTH_POINT_SIZE_RANGE = 1, 255

Compressed texture formats:
  0x86b0
  0x86b1
  0x83f0
  0x83f2
  0x83f3
```

**Comment by impaktor** [comment]
```
<magagnarata> anyways, the only issues I see are some missing textures and
              artifacts, so yeah                                        [16:02]
<impaktor> Do you have a screenshot of that?
```
https://imgur.com/a/873Gm

**Comment by fluffyfreak** [comment]
That's odd. It looks like it's not supporting dxtn textures.

Can I recommend that people try installing the libtxc library?
`sudo apt-get install libtxc-dxtn-s2tc0`

**Comment by impaktor** [comment]
He's already installed libtxc-dxtn-s2tc0, he says (and tested that it still doesn't work, I assume?).

**Comment by alex199568** [comment]
Here is opengl.txt

`OpenGL version 3.3 (Core Profile) Mesa 10.1.3, running on Intel Open Source Technology Center Mesa DRI Intel(R) Haswell Mobile 
Available extensions:
Shading language version: 3.30
  GL_ARB_ES2_compatibility
  GL_ARB_ES3_compatibility
  GL_ARB_base_instance
  GL_ARB_blend_func_extended
  GL_ARB_clear_buffer_object
  GL_ARB_copy_buffer
  GL_ARB_conservative_depth
  GL_ARB_debug_output
  GL_ARB_depth_buffer_float
  GL_ARB_depth_clamp
  GL_ARB_draw_buffers
  GL_ARB_draw_buffers_blend
  GL_ARB_draw_elements_base_vertex
  GL_ARB_draw_instanced
  GL_ARB_explicit_attrib_location
  GL_ARB_fragment_coord_conventions
  GL_ARB_fragment_shader
  GL_ARB_framebuffer_object
  GL_ARB_framebuffer_sRGB
  GL_ARB_get_program_binary
  GL_ARB_half_float_pixel
  GL_ARB_half_float_vertex
  GL_ARB_instanced_arrays
  GL_ARB_internalformat_query
  GL_ARB_invalidate_subdata
  GL_ARB_map_buffer_alignment
  GL_ARB_map_buffer_range
  GL_ARB_occlusion_query2
  GL_ARB_pixel_buffer_object
  GL_ARB_point_sprite
  GL_ARB_provoking_vertex
  GL_ARB_robustness
  GL_ARB_sample_shading
  GL_ARB_sampler_objects
  GL_ARB_seamless_cube_map
  GL_ARB_shader_atomic_counters
  GL_ARB_shader_bit_encoding
  GL_ARB_shader_objects
  GL_ARB_shader_texture_lod
  GL_ARB_shading_language_packing
  GL_ARB_shading_language_420pack
  GL_ARB_sync
  GL_ARB_texture_buffer_object
  GL_ARB_texture_buffer_object_rgb32
  GL_ARB_texture_buffer_range
  GL_ARB_texture_compression_rgtc
  GL_ARB_texture_cube_map_array
  GL_ARB_texture_float
  GL_ARB_texture_gather
  GL_ARB_texture_mirror_clamp_to_edge
  GL_ARB_texture_multisample
  GL_ARB_texture_non_power_of_two
  GL_ARB_texture_query_levels
  GL_ARB_texture_query_lod
  GL_ARB_texture_rectangle
  GL_ARB_texture_rgb10_a2ui
  GL_ARB_texture_rg
  GL_ARB_texture_storage
  GL_ARB_texture_storage_multisample
  GL_ARB_texture_swizzle
  GL_ARB_timer_query
  GL_ARB_uniform_buffer_object
  GL_ARB_vertex_array_bgra
  GL_ARB_vertex_array_object
  GL_ARB_vertex_attrib_binding
  GL_ARB_vertex_shader
  GL_ARB_vertex_type_10f_11f_11f_rev
  GL_ARB_vertex_type_2_10_10_10_rev
  GL_ARB_viewport_array
  GL_EXT_abgr
  GL_EXT_blend_equation_separate
  GL_EXT_draw_buffers2
  GL_EXT_draw_instanced
  GL_EXT_framebuffer_blit
  GL_EXT_framebuffer_multisample
  GL_EXT_framebuffer_multisample_blit_scaled
  GL_EXT_framebuffer_sRGB
  GL_EXT_packed_depth_stencil
  GL_EXT_packed_float
  GL_EXT_pixel_buffer_object
  GL_EXT_provoking_vertex
  GL_EXT_shader_integer_mix
  GL_EXT_texture_array
  GL_EXT_texture_compression_dxt1
  GL_ANGLE_texture_compression_dxt3
  GL_ANGLE_texture_compression_dxt5
  GL_EXT_texture_compression_rgtc
  GL_EXT_texture_compression_s3tc
  GL_EXT_texture_filter_anisotropic
  GL_EXT_texture_integer
  GL_EXT_texture_shared_exponent
  GL_EXT_texture_snorm
  GL_EXT_texture_sRGB
  GL_EXT_texture_sRGB_decode
  GL_EXT_texture_swizzle
  GL_EXT_timer_query
  GL_EXT_transform_feedback
  GL_EXT_vertex_array_bgra
  GL_OES_EGL_image
  GL_OES_read_format
  GL_KHR_debug
  GL_3DFX_texture_compression_FXT1
  GL_AMD_conservative_depth
  GL_AMD_draw_buffers_blend
  GL_AMD_seamless_cubemap_per_texture
  GL_AMD_shader_trinary_minmax
  GL_AMD_vertex_shader_layer
  GL_APPLE_object_purgeable
  GL_ATI_blend_equation_separate
  GL_ATI_texture_float
  GL_IBM_multimode_draw_arrays
  GL_MESA_pack_invert
  GL_MESA_texture_signed_rgba
  GL_NV_conditional_render
  GL_NV_depth_clamp
  GL_NV_packed_depth_stencil
  GL_S3_s3tc

Implementation Limits:
GL_MAX_COMBINED_TEXTURE_IMAGE_UNITS = 96
GL_MAX_CUBE_MAP_TEXTURE_SIZE = 2048
GL_MAX_DRAW_BUFFERS = 8
GL_MAX_ELEMENTS_INDICES = 3000
GL_MAX_ELEMENTS_VERTICES = 3000
GL_MAX_FRAGMENT_UNIFORM_COMPONENTS = 16384
GL_MAX_TEXTURE_IMAGE_UNITS = 32
GL_MAX_TEXTURE_LOD_BIAS = 14
GL_MAX_TEXTURE_SIZE = 8192
GL_MAX_VERTEX_ATTRIBS = 16
GL_MAX_VERTEX_TEXTURE_IMAGE_UNITS = 32
GL_MAX_VERTEX_UNIFORM_COMPONENTS = 16384
GL_NUM_COMPRESSED_TEXTURE_FORMATS = 5
GL_SAMPLE_BUFFERS = 0
GL_SAMPLES = 0
GL_ALIASED_LINE_WIDTH_RANGE = 1, 5
GL_MAX_VIEWPORT_DIMS = 16384, 16384
GL_SMOOTH_LINE_WIDTH_RANGE = 1, 5
GL_SMOOTH_POINT_SIZE_RANGE = 1, 255

Compressed texture formats:
  0x86b0
  0x86b1
  0x83f0
  0x83f2
  0x83f3`

I tried `sudo apt-get install libtxc-dxtn-s2tc0` . I got 
`
alex@g50-70:~/.pioneer$ sudo apt-get install libtxc-dxtn-s2tc0
[sudo] password for alex: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libtxc-dxtn-s2tc0 is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 138 not upgraded.
alex@g50-70:~/.pioneer$ 
`

**Comment by alex199568** [comment]
Also, here is output. It was not with opengl.txt . It's what was printed to the console.
`
Making all in contrib
make[1]: Entering directory `/home/alex/Documents/code/pioneer/pioneer/contrib'
Making all in lua
make[2]: Entering directory `/home/alex/Documents/code/pioneer/pioneer/contrib/lua'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/home/alex/Documents/code/pioneer/pioneer/contrib/lua'
Making all in miniz
make[2]: Entering directory `/home/alex/Documents/code/pioneer/pioneer/contrib/miniz'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/home/alex/Documents/code/pioneer/pioneer/contrib/miniz'
Making all in jenkins
make[2]: Entering directory `/home/alex/Documents/code/pioneer/pioneer/contrib/jenkins'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/home/alex/Documents/code/pioneer/pioneer/contrib/jenkins'
Making all in json
make[2]: Entering directory `/home/alex/Documents/code/pioneer/pioneer/contrib/json'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/home/alex/Documents/code/pioneer/pioneer/contrib/json'
Making all in PicoDDS
make[2]: Entering directory `/home/alex/Documents/code/pioneer/pioneer/contrib/PicoDDS'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/home/alex/Documents/code/pioneer/pioneer/contrib/PicoDDS'
Making all in vcacheopt
make[2]: Entering directory `/home/alex/Documents/code/pioneer/pioneer/contrib/vcacheopt'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/home/alex/Documents/code/pioneer/pioneer/contrib/vcacheopt'
Making all in profiler
make[2]: Entering directory `/home/alex/Documents/code/pioneer/pioneer/contrib/profiler'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/home/alex/Documents/code/pioneer/pioneer/contrib/profiler'
make[2]: Entering directory `/home/alex/Documents/code/pioneer/pioneer/contrib'
make[2]: Nothing to be done for `all-am'.
make[2]: Leaving directory `/home/alex/Documents/code/pioneer/pioneer/contrib'
make[1]: Leaving directory `/home/alex/Documents/code/pioneer/pioneer/contrib'
Making all in src
make[1]: Entering directory `/home/alex/Documents/code/pioneer/pioneer/src'
Making all in collider
make[2]: Entering directory `/home/alex/Documents/code/pioneer/pioneer/src/collider'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/home/alex/Documents/code/pioneer/pioneer/src/collider'
Making all in gui
make[2]: Entering directory `/home/alex/Documents/code/pioneer/pioneer/src/gui'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/home/alex/Documents/code/pioneer/pioneer/src/gui'
Making all in graphics
make[2]: Entering directory `/home/alex/Documents/code/pioneer/pioneer/src/graphics'
Making all in opengl
make[3]: Entering directory `/home/alex/Documents/code/pioneer/pioneer/src/graphics/opengl'
make[3]: Nothing to be done for `all'.
make[3]: Leaving directory `/home/alex/Documents/code/pioneer/pioneer/src/graphics/opengl'
Making all in dummy
make[3]: Entering directory `/home/alex/Documents/code/pioneer/pioneer/src/graphics/dummy'
make[3]: Nothing to be done for `all'.
make[3]: Leaving directory `/home/alex/Documents/code/pioneer/pioneer/src/graphics/dummy'
make[3]: Entering directory `/home/alex/Documents/code/pioneer/pioneer/src/graphics'
make[3]: Nothing to be done for `all-am'.
make[3]: Leaving directory `/home/alex/Documents/code/pioneer/pioneer/src/graphics'
make[2]: Leaving directory `/home/alex/Documents/code/pioneer/pioneer/src/graphics'
Making all in galaxy
make[2]: Entering directory `/home/alex/Documents/code/pioneer/pioneer/src/galaxy'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/home/alex/Documents/code/pioneer/pioneer/src/galaxy'
Making all in scenegraph
make[2]: Entering directory `/home/alex/Documents/code/pioneer/pioneer/src/scenegraph'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/home/alex/Documents/code/pioneer/pioneer/src/scenegraph'
Making all in terrain
make[2]: Entering directory `/home/alex/Documents/code/pioneer/pioneer/src/terrain'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/home/alex/Documents/code/pioneer/pioneer/src/terrain'
Making all in text
make[2]: Entering directory `/home/alex/Documents/code/pioneer/pioneer/src/text'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/home/alex/Documents/code/pioneer/pioneer/src/text'
Making all in ui
make[2]: Entering directory `/home/alex/Documents/code/pioneer/pioneer/src/ui'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/home/alex/Documents/code/pioneer/pioneer/src/ui'
Making all in gameui
make[2]: Entering directory `/home/alex/Documents/code/pioneer/pioneer/src/gameui'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/home/alex/Documents/code/pioneer/pioneer/src/gameui'
Making all in posix
make[2]: Entering directory `/home/alex/Documents/code/pioneer/pioneer/src/posix'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/home/alex/Documents/code/pioneer/pioneer/src/posix'
make[2]: Entering directory `/home/alex/Documents/code/pioneer/pioneer/src'
make[2]: Nothing to be done for `all-am'.
make[2]: Leaving directory `/home/alex/Documents/code/pioneer/pioneer/src'
make[1]: Leaving directory `/home/alex/Documents/code/pioneer/pioneer/src'
Making all in data
make[1]: Entering directory `/home/alex/Documents/code/pioneer/pioneer/data'
make[1]: Nothing to be done for `all'.
make[1]: Leaving directory `/home/alex/Documents/code/pioneer/pioneer/data'
Making all in osx
make[1]: Entering directory `/home/alex/Documents/code/pioneer/pioneer/osx'
make[1]: Nothing to be done for `all'.
make[1]: Leaving directory `/home/alex/Documents/code/pioneer/pioneer/osx'
make[1]: Entering directory `/home/alex/Documents/code/pioneer/pioneer'
make[1]: Nothing to be done for `all-am'.
make[1]: Leaving directory `/home/alex/Documents/code/pioneer/pioneer'
ver git (fdf528d) on: Linux

System Name: Linux
Host Name: g50-70
Release(Kernel) Version: 3.13.0-63-generic
Kernel Build Timestamp: #103-Ubuntu SMP Fri Aug 14 21:42:59 UTC 2015
Machine Arch: x86_64
Domain Name: (none)

SDL Version 2.0.3
Failed to set video mode. (Couldn't find matching GLX visual). Re-trying without multisampling.
Initialized OpenGL 3.1, with extensions, renderer
invalid axis binding '' in config file for BindAxisPitch
invalid axis binding '' in config file for BindAxisRoll
invalid axis binding '' in config file for BindAxisYaw
started 3 worker threads
ShipType::Init()
Lua::Init()
Server agent disabled
GalaxyGenerator::Init()
Creating new galaxy generator 'legacy' version 1
Number of factions added: 103
StarSystemCache: misses: 2227, slave hits: 0, master hits: 0
SectorCache: misses: 1571, slave hits: 0, master hits: 11138
FaceParts::Init()
Face Generation source images loaded.
new ModelCache
Shields::Init
BaseSphere::Init
CityOnPlanet::Init
CreateCollisionMesh for : (kbuilding01)
CreateCollisionMesh for : (kbuilding02)
CreateCollisionMesh for : (kbuilding03)
CreateCollisionMesh for : (newbuilding1)
CreateCollisionMesh for : (newbuilding10)
CreateCollisionMesh for : (newbuilding11)
CreateCollisionMesh for : (newbuilding2)
CreateCollisionMesh for : (newbuilding3)
CreateCollisionMesh for : (newbuilding4)
CreateCollisionMesh for : (newbuilding5)
CreateCollisionMesh for : (newbuilding6)
CreateCollisionMesh for : (newbuilding7)
CreateCollisionMesh for : (newbuilding8)
CreateCollisionMesh for : (newbuilding9)
Got 14 buildings of tag city_building
 - kbuilding01: 29.664692
 - kbuilding02: 46.268344
 - kbuilding03: 41.542333
 - newbuilding1: 36.202756
 - newbuilding10: 16.297418
 - newbuilding11: 34.961034
 - newbuilding2: 22.822782
 - newbuilding3: 22.649894
 - newbuilding4: 25.978193
 - newbuilding5: 22.908506
 - newbuilding6: 29.817877
 - newbuilding7: 22.674426
 - newbuilding8: 23.154979
 - newbuilding9: 36.528138
End of buildings.
SpaceStation::Init
CreateCollisionMesh for : (ground_station)
ground_station has:
 14 entrances,
 14 pads,
 0 exits
CreateCollisionMesh for : (new_ground)
new_ground has:
 6 entrances,
 6 pads,
 0 exits
CreateCollisionMesh for : (orbital_station_2-10k)
orbital_station_2-10k has:
 5 entrances,
 64 pads,
 5 exits
CreateCollisionMesh for : (orbital_station_2-2k)
orbital_station_2-2k has:
 4 entrances,
 18 pads,
 4 exits
CreateCollisionMesh for : (orbital_station_2-5k)
orbital_station_2-5k has:
 5 entrances,
 64 pads,
 5 exits
CreateCollisionMesh for : (orbital_station_2-5k10k)
orbital_station_2-5k10k has:
 5 entrances,
 64 pads,
 5 exits
NavLights::Init
Sfx::Init
Sound::Init


Loading took: 16082.319513 milliseconds
CreateCollisionMesh for : (ac33)
CreateCollisionMesh for : (amphiesma)
CreateCollisionMesh for : (deneb)
CreateCollisionMesh for : (dsminer)
CreateCollisionMesh for : (kanara_civ)
CreateCollisionMesh for : (lunarshuttle)
CreateCollisionMesh for : (malabar)
CreateCollisionMesh for : (molamola)
CreateCollisionMesh for : (natrix)
CreateCollisionMesh for : (nerodia)
CreateCollisionMesh for : (pumpkinseed)
CreateCollisionMesh for : (sinonatrix)
CreateCollisionMesh for : (storeria)
CreateCollisionMesh for : (varada)
CreateCollisionMesh for : (vatakara)
CreateCollisionMesh for : (venturestar)
CreateCollisionMesh for : (wave)
CreateCollisionMesh for : (xylophis)
StarSystemCache: misses: 0, slave hits: 0, master hits: 0
SectorCache: misses: 101, slave hits: 0, master hits: 1
`

This output was made with warning commented out, usually there are also lines about GL_INVALID_ENUM.

**Comment by impaktor** [comment]
> He's already installed libtxc-dxtn-s2tc0, he says (and tested that it still doesn't work, I assume?).

Yes, confirmed by him, problem still remains after install and reboot. (he commented out the warnings in RendererGL.cpp)

**Comment by fluffyfreak** [comment]
@alex199568 ok and it's a Sandy Bridge Intel CPU/GPU combo with no other GPU in the system?
What CPU is it exactly, i.e. the model number if you know it?

**Comment by impaktor** [comment]
magagnarata has an asus x55c laptop, with cpu intel core i3-2328m, gpu sandybridge mobile, no other gpus

**Comment by fluffyfreak** [comment]
Pastebin info from 'maxrebo' via IRC, [output](http://pastebin.com/KbFf1zMr) and [opengl](http://pastebin.com/hSyLSYX6)

**Comment by fluffyfreak** [comment]
This is a snippet with 'EnableGLDebug=1' set in the 'config.ini', it seems to show us making a lot of calls to deprecated functions however these do not appear in the codebase anymore!

```
ver 20151104 (e8a3587) on: Windows

Hardware information: 
  		OEM ID: 0
  		Number of processors: 8
  		Page size: 4096
  		Processor type: 586
  		Minimum application address: 00010000
  		Maximum application address: 7ffeffff
  		Active processor mask: 255

Windows 7
SDL Version 2.0.3
Initialized OpenGL 3.1, with extensions, renderer
invalid axis binding '' in config file for BindAxisPitch
invalid axis binding '' in config file for BindAxisRoll
invalid axis binding '' in config file for BindAxisYaw
started 7 worker threads
ShipType::Init()
Lua::Init()
Server agent disabled
Type: Other, Source: API, ID: 131185, Severity: , Message: Buffer detailed info: Buffer object 1 (bound to GL_ARRAY_BUFFER_ARB, usage hint is GL_STATIC_DRAW) will use VIDEO memory as the source for buffer object operations.
Type: Other, Source: API, ID: 131185, Severity: , Message: Buffer detailed info: Buffer object 2 (bound to GL_ARRAY_BUFFER_ARB, usage hint is GL_STATIC_DRAW) will use VIDEO memory as the source for buffer object operations.
Type: Other, Source: API, ID: 131185, Severity: , Message: Buffer detailed info: Buffer object 2 (bound to GL_VERTEX_ATTRIB_ARRAY_BUFFER_BINDING_ARB (0), GL_VERTEX_ATTRIB_ARRAY_BUFFER_BINDING_ARB (3), and GL_ARRAY_BUFFER_ARB, usage hint is GL_STATIC_DRAW) has been mapped in HOST memory.
Type: Other, Source: API, ID: 131185, Severity: , Message: Buffer detailed info: Buffer object 2 (bound to GL_VERTEX_ATTRIB_ARRAY_BUFFER_BINDING_ARB (0), and GL_VERTEX_ATTRIB_ARRAY_BUFFER_BINDING_ARB (3), usage hint is GL_STATIC_DRAW) stored in SYSTEM HEAP memory has been updated.
Type: Other, Source: API, ID: 131185, Severity: , Message: Buffer detailed info: Buffer object 2 (bound to GL_VERTEX_ATTRIB_ARRAY_BUFFER_BINDING_ARB (0), and GL_VERTEX_ATTRIB_ARRAY_BUFFER_BINDING_ARB (3), usage hint is GL_STATIC_DRAW) will use SYSTEM HEAP memory as the source for buffer object operations.
Type: Other, Source: API, ID: 131185, Severity: , Message: Buffer detailed info: Buffer object 2 (bound to GL_VERTEX_ATTRIB_ARRAY_BUFFER_BINDING_ARB (0), and GL_VERTEX_ATTRIB_ARRAY_BUFFER_BINDING_ARB (3), usage hint is GL_STATIC_DRAW) will use SYSTEM HEAP memory as the source for buffer object operations.
Type: Error, Source: API, ID: 1282, Severity: High, Message: GL_INVALID_OPERATION error generated. Function glPushAttrib is deprecated and not available in preview contexts.
Type: Error, Source: API, ID: 1280, Severity: High, Message: GL_INVALID_ENUM error generated. Cannot enable <cap> in the current profile.
Type: Error, Source: API, ID: 1280, Severity: High, Message: GL_INVALID_ENUM error generated. Cannot enable <cap> in the current profile.
Type: Error, Source: API, ID: 1280, Severity: High, Message: GL_INVALID_ENUM error generated. Cannot enable <cap> in the current profile.
Type: Error, Source: API, ID: 1280, Severity: High, Message: GL_INVALID_ENUM error generated. Cannot enable <cap> in the current profile.
Type: Error, Source: API, ID: 1280, Severity: High, Message: GL_INVALID_ENUM error generated. Cannot enable <cap> in the current profile.
Type: Error, Source: API, ID: 1280, Severity: High, Message: GL_INVALID_ENUM error generated. Cannot enable <cap> in the current profile.
Type: Error, Source: API, ID: 1282, Severity: High, Message: GL_INVALID_OPERATION error generated. Function glMatrixMode is deprecated and not available in preview contexts.
Type: Error, Source: API, ID: 1282, Severity: High, Message: GL_INVALID_OPERATION error generated. Function glPushMatrix is deprecated and not available in preview contexts.
Type: Error, Source: API, ID: 1282, Severity: High, Message: GL_INVALID_OPERATION error generated. Function glLoadIdentity is deprecated and not available in preview contexts.
Type: Error, Source: API, ID: 1282, Severity: High, Message: GL_INVALID_OPERATION error generated. Function glOrtho is deprecated and not available in preview contexts.
Type: Error, Source: API, ID: 1282, Severity: High, Message: GL_INVALID_OPERATION error generated. Function glMatrixMode is deprecated and not available in preview contexts.
Type: Error, Source: API, ID: 1282, Severity: High, Message: GL_INVALID_OPERATION error generated. Function glPushMatrix is deprecated and not available in preview contexts.
Type: Error, Source: API, ID: 1282, Severity: High, Message: GL_INVALID_OPERATION error generated. Function glLoadIdentity is deprecated and not available in preview contexts.
Type: Error, Source: API, ID: 1282, Severity: High, Message: GL_INVALID_OPERATION error generated. Function glMatrixMode is deprecated and not available in preview contexts.
Type: Error, Source: API, ID: 1282, Severity: High, Message: GL_INVALID_OPERATION error generated. Function glPushMatrix is deprecated and not available in preview contexts.
Type: Error, Source: API, ID: 1282, Severity: High, Message: GL_INVALID_OPERATION error generated. Function glLoadIdentity is deprecated and not available in preview contexts.
Type: Error, Source: API, ID: 1282, Severity: High, Message: GL_INVALID_OPERATION error generated. Function glBegin is deprecated and not available in preview contexts.
Type: Error, Source: API, ID: 1282, Severity: High, Message: GL_INVALID_OPERATION error generated. Function glColor4f is deprecated and not available in preview contexts.
```

**Comment by impaktor** [comment]
> a lot of calls to deprecated functions however these do not appear in the codebase anymore!

Technically, they're in the code _somewhere_, right? Just as a sanity test you're on top of this (see below)?

```
[~/usr/src/pioneer]% git grep glPushMatrix                                                               [git][better_cargorun]
src/graphics/opengl/gl_core_3_x.c:void (CODEGEN_FUNCPTR *_ptrc_glPushMatrix)() = NULL;
src/graphics/opengl/gl_core_3_x.c:   _ptrc_glPushMatrix = (void (CODEGEN_FUNCPTR *)())IntGetProcAddress("glPushMatrix");
src/graphics/opengl/gl_core_3_x.c:   if(!_ptrc_glPushMatrix) numFailed++;
src/graphics/opengl/gl_core_3_x.h:extern void (CODEGEN_FUNCPTR *_ptrc_glPushMatrix)();
src/graphics/opengl/gl_core_3_x.h:#define glPushMatrix _ptrc_glPushMatrix
```

```
[~/usr/src/pioneer]% git grep glOrtho                                                                    [git][better_cargorun]
src/graphics/opengl/gl_core_3_x.c:void (CODEGEN_FUNCPTR *_ptrc_glOrtho)(GLdouble, GLdouble, GLdouble, GLdouble, GLdouble, GLdouble) = NULL;
src/graphics/opengl/gl_core_3_x.c:   _ptrc_glOrtho = (void (CODEGEN_FUNCPTR *)(GLdouble, GLdouble, GLdouble, GLdouble, GLdouble, GLdouble))IntGetProcAddress("glOrtho");
src/graphics/opengl/gl_core_3_x.c:   if(!_ptrc_glOrtho) numFailed++;
src/graphics/opengl/gl_core_3_x.h:extern void (CODEGEN_FUNCPTR *_ptrc_glOrtho)(GLdouble, GLdouble, GLdouble, GLdouble, GLdouble, GLdouble);
src/graphics/opengl/gl_core_3_x.h:#define glOrtho _ptrc_glOrtho
src/matrix4x4.h: // set a orthographic frustum with 6 params similar to glOrtho()
```

Or this has nothing to do with it?

**Comment by fluffyfreak** [comment]
Yeah I know about them, they're in the header that we pull in to linkup the OpenGL function pointers. 

I've built a newer version of the gl_core_3_x files with `core` instead of `compatbility` profiles That removes all of the aforementioned function pointers. maxrebo tested that last night too but sadly it still fails.

I'll be doing a PR to switch to that `core` build at some point soon but I didn't have time last night.

**Comment by fluffyfreak** [comment]
NB: the #3514 PR won't fix this issue so if it gets closed then please re-open it.

**Comment by impaktor** [comment]
Fixed by:

```
<maxrebo> I got it figured out, and as expected it WAS a problem on my end
<maxrebo> I use MSI Afterburner to undervolt my GPU, which uses Riva Tuner 
          for ion overlaying an OSD
<maxrebo> ...which in turn uses old deprecated OpenGL immediate mode calls
<maxrebo> so there's nothing wrong with the code
```

> if it gets closed then please re-open it.

Github only closes an issue if you in the merge use the word _close_, _closes_. _fix_, or _fixes_, just before the issue number reference, so should be fine.

**Comment by fluffyfreak** [comment]
OMG!!!

**Comment by fluffyfreak** [comment]
Hmm, on the downside, that means that the Linux issues are still unresolved :/

**Comment by fluffyfreak** [comment]
After several hours of `magagnarata` very helpfully trying out numerous ideas and using gdb to track down the problem it seems like some Intel GPUs aren't enjoying how we build and compress textures.

Whenever it has to compress a texture and generate it's mipmaps, or generate mipmaps for a compressed texture loaded from file, it fails and causes the OpenGL errors.

**Comment by fluffyfreak** [comment]
I think I will construct a test case to try out on other machines and to track down a machine that I can use for testing for myself.

**Comment by fluffyfreak** [comment]
Hooray for Intel and their suck-ass drivers/GPU's.

I can now reproduce this problem on a Linux (Mint) machine.

**Comment by fluffyfreak** [comment]
This might even be the cause of #3439 as well since that's using Intel GPU's too just on Windows.

**Comment by fluffyfreak** [comment]
@jaj22 dragging your attention here from #3881 since this is the original Intel texture issues thread :)

What I've found tonight is that I'm getting these warnings popup with DDS textures and PNG files so something is rotten in the texture loading code.

**Comment by fluffyfreak** [comment]
The only configuration of hardware and software taht I've been able to get this kind of error on is an `Intel i5-5200U` with `Broadwell-U Integrated Graphics` whilst running `Linux Mint 17.2 Cinnamon 64-bit`.

Just in case anyone has similar hardware / OS etc.

**Comment by jaj22** [comment]
For what it's worth, I get no warnings or errors on an older Sandybridge-architecture GPU (G620) with Mint 18 (Cinnamon, 64bit). This appears to have a much newer Intel driver: It reports OpenGL 3.3, Mesa 11.2.0.

I could try reinstalling with Mint 17.2, although from a user perspective I'd recommend just installing the driver that works. Pioneer may not be doing anything wrong.

**Comment by jaj22** [comment]
Ok, stock Mint 17.2 on the G620 replicates this issue _and_ #3881.

#3881 is simply caused by that driver version not supporting shaders with version >140. The ImgUI GL3 shaders specify version 330. They're trivial shaders so you can just change the version to 140 to fix the problem.

The INVALID_ENUM warnings are caused by called glGenerateMipmap on compressed textures, but apparently not all of them. They're only triggering with two texture sizes here: 16x1 and 32x32. I'm not sure what the 16x1 texture is, but I somehow doubt it's supposed to be compressed. 32x32 might be a driver glitch.

**Comment by jaj22** [comment]
Looks like glGenerateMipmap fails on all compressed textures with those drivers. This includes the 1024x4 gas giant textures (more colour maps?) and various decals. Mipmap generation does work on the handful of ship textures that don't have a compressed target.

As far as I can tell, this behaviour doesn't follow the GL spec. The same function in invalid for compressed textures in GL ES, but not in any GL version. If we want to work around it, we can test at startup by creating small compressed textures for various formats and calling glGenerateMipmaps on them. I don't think there's any obvious tell in the implementation limits or extension lists.

From a user perspective, simply setting UseTextureCompression=0 is a valid workaround, as compressed but non-mipmapped textures are not used anywhere in Pioneer.

**Comment by richardpl** [comment]
We should probably close this bug report, as it is not our bug.

**Comment by impaktor** [comment]
I'll leave it to @fluffyfreak to close. Andy: start reading your comment from 10th november above to get insight as to what this is about.

**Comment by fluffyfreak** [comment]
This is actually two different bugs. The first was the Riva Tuner issue but the second is to do with Intel drivers for certain versions of their GPUs.

That's certainly their fault but it's something that we could work around by generating our own mip chain before compressing the textures, or taking over both and doing both mip chain & compression before handing over to OpenGL.

**Comment by impaktor** [comment]
> That's certainly their fault but it's something that we could work around

Is this something we (read: you) want to do? Might many users be effected by this bug? If itthe fix will uglifying the code much, or is more than some small fix then I'd vote close. I'll leave the decision up to you.

**Comment by fluffyfreak** [comment]
Ok, going to close the issue for now.
