### ISSUE TITLE
Space station docks full

### ISSUE THREAD

**Issue by fgfs-fmanu** [pioneerspacesim/pioneer#5427]
Hello. I would like to report a problem:

After our conversation on the forum: [https://spacesimcentral.com/community/pioneer/space-station-docks-full/#post-62505](https://spacesimcentral.com/community/pioneer/space-station-docks-full/)

### Observed behaviour

While making deliveries, i found many space stations full. It began with space stations of earth like Jobs Pad, or Gates Spaceport. But it spread to bases on Earth, on the ground. Now i have the same problem with stations around Jupiter orbit. The problem is that i can not finnish my missions.

![Capture d’écran_2022-11-20_14-41-19](https://user-images.githubusercontent.com/64139564/203650432-c87516ae-93a9-4ac5-a222-7e44e87c2562.png)

### Expected behaviour

It would be great if there is place to dock or land on spaceport. At least one free dock to be able to finish mission. Or if spaceports are full, they would stay full for a short time.

I tried to join my save state. I added .zip at the end of the name, for the file format is supported in the message. You can remove the .zip extension before using it.

[_exit.zip](https://github.com/pioneerspacesim/pioneer/files/10079343/_exit.zip)

Thank you for reading my problem.

__My pioneer version (and OS):__

pioneer 20220919
--------------------
SDL Version (build) 2.24.0
SDL Version (dynamic) 2.24.2
WARNING: SDL Versions differ
SDL_image Version (build): 2.6.2
SDL_image Version (dynamic): 2.6.2
SDL_image Versions match
Assimp Version: 5.2.0
FreeType Version: 2.12.1
GLEW dynamic version: 2.2.0
--------------------

OS : Archlinux

**Comment by Gliese852** [comment]
@fgfs-fmanu  Unable to load your savegame into the _~September 19th_ version, perhaps the build was made on that day, but the sources were older.

Please specify more precisely the version of the game, where did you get it? if compiled from git sources, specify the commit hash.

**Comment by fgfs-fmanu** [comment]
I updated my version. I saw my saves corrupted. I started a new game. It should work fine. Maybe i installed the game from snap.

Thank you for your help

**Comment by Gliese852** [comment]
@fgfs-fmanu I was able to load your savegame, all docked ships have no AI control at all, it's not clear how this happened. About 1800 ships were "lost" for the game. I was never able to reproduce the loss of AI control of even one ship.

Could you please describe in more detail what you did in the game, how often you saved, whether you jumped to other systems,  maybe something special?

**Comment by fgfs-fmanu** [comment]
Sorry for the answer time. I though the problem was solved. I met this problem again.

![Capture d’écran_2022-12-07_20-22-39](https://user-images.githubusercontent.com/64139564/206276953-f06ae100-e42b-4946-bfb0-c3335e12551a.png)

On the game, i'm doing only deliveries. I don't go outside from the solar system, so no hyperspace. I activate autosave so it saves every time i dock and undock.  I send in the attachment the preferences i set. Maybe it can help. I do trips on maximum warp time, and on autopilot.

![Capture d’écran_2022-12-07_20-25-02](https://user-images.githubusercontent.com/64139564/206277053-41f657e1-2ee8-4f54-b56f-093aa37a76ad.png)

On archlinux, i could choose two versions from AUR pioneer-bin and pioneer. This is the version i installed, pioneer:

https://aur.archlinux.org/packages/pioneer

I hope i could give enough informations.

Thank you for your help.

**Comment by impaktor** [comment]
> I though the problem was solved.
>  This is the version i installed, pioneer: https://aur.archlinux.org/packages/pioneer

That's still the February version, almost one year old, so if the docking problem is fixed, it will not be in that version. 
(Also, that link can change version in future, so better post commit hash, or build date)

**Comment by retronica** [comment]
This problem persists even in a recent compile from git.

I like to play the hard gamestart and if I either stay in Barnards Star (doing in-system runs), or goto Sol (sell drive and do in-system runs) after a while the busiest ports become unusable (BS: OPLI Pax & Systems Admin Resting; Sol: Gates Spaceprot & Jobs Pad). 

They remain full and ships never leave the docks, even after _months_ of gametime.

**Comment by Gliese852** [comment]
@fgfs-fmanu @retronica I still find it difficult to determine how this happens, because I can not reproduce it. While I can offer you the following workaround - open the console `~` and paste the following there:
```
for _, bad in pairs(require'Space'.GetBodies(function (body) return body:IsShip() and not require 'modules.TradeShips.Core'.ships[body] end)) do bad:Explode() end
```
this will destroy all the "lost" ships, and in about a month the situation will stabilize.

did you hyperjump to another system at least once in a game, or did you stay in one system all the time?

**Comment by retronica** [comment]
@Gliese852 - I can confirm the workaround explodes all the zombie ships filling up the docking bays - greatly appreciated.

> I still find it difficult to determine how this happens, because I can not reproduce it. 

I imagine you would just need to spend a long while (a few in-game months) in the same system, preferably a busy one. The kind of gamestyle which would be expected of a hard game start. (in-system runs in the starting system [or a nearby you major one] until you get enough money [~$30K] for a decent courier ship).

In my most recent game I never left Barnards Star, and it occured by early Feb 3223, where some stations would be hard and then impossible to land at (eg. OPLI Pax, HSP Serenity, & Systems Admin Resting).

>did you hyperjump to another system at least once in a game, or did you stay in one system all the time?
I have seen it occur in both cases.

**Comment by Gliese852** [comment]
I was able to reproduce and find (it seems) the cause of this problem - it is described in the corresponding PR (#5456). 

To avoid this in the current version of the game, you need to either manually save/load the game, or not resume the game via 'Continue', but manually load the most recent `_autosave`

Either you can compile this branch
https://github.com/Gliese852/pioneer/tree/full-docks
or you can download the artifacts from the page:
https://github.com/pioneerspacesim/pioneer/actions/runs/3774551623

I think the savegame will be compatible with the current master, but will not be compatible with 20220203
