### ISSUE TITLE
Ship Capacity on Station Market screen doesn't match Cargo Capacity in Ship Info

### ISSUE THREAD

**Issue by Bodasey** [pioneerspacesim/pioneer#5478]
### Observed behaviour

Bulletin Board and Commodity Market display the allover free capacity as in the equipment market.
(differs a lot with a low equipped coronatrix ship)

### Expected behaviour

Bulletin Board and Commodity Market should display the free cargo space as in personal info -> Commodity and trade
In the equipment market, another symbol should be used aside the percent character.

__My pioneer version (and OS):__
actual master

**Comment by Bodasey** [comment]
Fuel scooping should also have a look to free cargo space first, and not the allover capacity and then realize there's no free space for the hydrogen to fit into.
![HowManyTonsH2](https://user-images.githubusercontent.com/60466586/213268161-7d4770b9-2fc1-42c0-b01e-3f53c98d9f2c.png)

**Comment by nozmajner** [comment]
The difference between cargo capacity and overall capacity is a somewhat clumsy way!to differentiate between ships a bit more. Capacity includes equipment space and cargo capacity. Two parts of a Venn diagram overlapping toma certain level.
In a sense it is an attempt to make ships not being about a single stat, not to be a shell where you can just shove in everything without structure.
The aim is to transition towards a more slot/hardpoint based approach where cargo capacity is mostly divorced from equipment.

**Comment by Web-eWorks** [comment]
Assigning @nozmajner to work on mockups to more clearly show cargo vs. equipment space in StationView contexts where that information is required.

**Comment by nozmajner** [comment]
Roger roger

**Comment by Digit** [comment]
(8691843e1)

Changed ship, to an AC-33, and seems afflicted with this bug too.  

[No effect on station's capacity readout from refuelling.  Capacity says 293t free, but isn't and cant buy more.  Station's Lobby window's main fuel bars, and Ship's Economy and Cargo windows all show it correctly.]

Does it only happen on some ships?  Consistently?  Or something unrelated to ship model, triggering this?

**Comment by bszlrd** [comment]
It happens to all ships. There's an overall capacity for cargo and equipment, and the cargo capacity is a subset of that. 
We want to move to a hardpoint based equipment system, which would solve this mostly.

**Comment by bszlrd** [comment]
I think this one was solved with the equipment rewrite.

**Comment by sturnclaw** [comment]
This is actually not fixed - in the current release, the capacity bar at the bottom of the station view shows the ship's equipment capacity regardless of the active view, which is useless information at best and can lead to some confusion when viewing the Commodity Market tab, for example.

This is an issue to be resolved by the station UI redesign or an interim solution which allows each individual tab to determine what capacity bar they'd like to show while the tab is active.

**Comment by bszlrd** [comment]
Oh, sorry then
